approvedGitRepositories:
  - "https://github.com/lipemat/*"

enableGlobalCache: true

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 2d

pnpEnableEsmLoader: false

supportedArchitectures:
  os:
    - current
    - linux
