// Autogenerated by typings-for-css-modules-loader.
declare namespace BasicPcssNamespace {
	export interface IBasicPcss {
		'some-class': string;
		someClass: string;
		'sub-class': string;
		subClass: string;
	}
}

declare const BasicPcssModule: BasicPcssNamespace.IBasicPcss;

export = BasicPcssModule;
