// Autogenerated by typings-for-css-modules-loader.
declare namespace FocusVisiblePcssNamespace {
	export interface IFocusVisiblePcss {
		focused: string;
	}
}

declare const FocusVisiblePcssModule: FocusVisiblePcssNamespace.IFocusVisiblePcss;

export = FocusVisiblePcssModule;
