// Autogenerated by typings-for-css-modules-loader.
declare namespace MediaQueriesLegacyPcssNamespace {
	export interface IMediaQueriesLegacyPcss {
		'genesis-nav-menu': string;
		genesisNavMenu: string;
		header: string;
		second: string;
	}
}

declare const MediaQueriesLegacyPcssModule: MediaQueriesLegacyPcssNamespace.IMediaQueriesLegacyPcss;

export = MediaQueriesLegacyPcssModule;
