// Autogenerated by typings-for-css-modules-loader.
declare namespace UndefinedPcssNamespace {
	export interface IUndefinedPcss {
		wrap: string;
	}
}

declare const UndefinedPcssModule: UndefinedPcssNamespace.IUndefinedPcss;

export = UndefinedPcssModule;
