process.env.BABEL_ENV = 'development';
process.env.NODE_ENV = 'development';

const webpack = require( 'webpack' );
const config = require( '../helpers/package-config' );
const {unlinkSync, writeFile} = require( 'fs' );
const WebpackDevServer = require( 'webpack-dev-server' );
const configHelper = require( '../helpers/config.cts' );
const path = require( 'path' );
const webpackConfig = configHelper.getConfig( 'webpack.dev' );
const devServerConfig = configHelper.getConfig( 'dev-server.config' );

const server = new WebpackDevServer( devServerConfig, webpack( webpackConfig ) );

/**
 * Create a `.running` file within the `dist` which only
 * exists if this script is running.
 */
writeFile( path.resolve( config.workingDirectory, 'dist/.running' ), new Date().toLocaleString() + '\n' + 'Generated by @lipemat/js-boilerplate.', err => {
	if ( err ) {
		throw err;
	}
	process.on( 'exit', () => {
		unlinkSync( path.resolve( config.workingDirectory, 'dist/.running' ) );
	} );
} );

( async() => {
	try {
		await server.start();
	} catch ( err ) {
		return console.log( err );
	}
} )();
