// Autogenerated by typings-for-css-modules-loader.
declare namespace MediaQueriesPcssNamespace {
	export interface IMediaQueriesPcss {
		'genesis-nav-menu': string;
		genesisNavMenu: string;
		header: string;
		second: string;
	}
}

declare const MediaQueriesPcssModule: MediaQueriesPcssNamespace.IMediaQueriesPcss;

export = MediaQueriesPcssModule;
